#!/bin/sh
CONF=/etc/config/qpkg.conf
QPKG_NAME="mykodi17"
QPKG_VERSION_NAME=$(/sbin/getcfg -f $CONF $QPKG_NAME QPKG_VERSION_NAME)
INSTALL_PATH=`/sbin/getcfg -f $CONF $QPKG_NAME Install_Path`

# iff invoked inside CHROOT environment
[ -z "$CHROOT_DIR" -o -z "$QPKG_CLASS" ] && exit 1

ENABLED=$(/sbin/getcfg $QPKG_NAME Enable -u -d FALSE -f $CONF)
if [ "$ENABLED" != "TRUE" ]; then
    echo "$QPKG_NAME is disabled."
    exit 1
fi

[ -e /opt/$QPKG_VERSION_NAME ] && rm -rf /opt/$QPKG_VERSION_NAME
ln -sf "$INSTALL_PATH/opt/$QPKG_VERSION_NAME" /opt/$QPKG_VERSION_NAME

[ -d /opt/startup_shell ] || mkdir -p /opt/startup_shell
ln -sf "$INSTALL_PATH/startup_shell/startup_${QPKG_NAME}.sh" /opt/startup_shell/startup_${QPKG_NAME}.sh
ln -sf "$INSTALL_PATH/startup_shell/stop_${QPKG_NAME}.sh" /opt/startup_shell/stop_${QPKG_NAME}.sh

export HOME=/share/homes/newkodi17
if [ ! -e $HOME/.kodi ] ; then
	mkdir .kodi
fi
